name: Create GKE + Flux (CLI)

on:
  workflow_dispatch:
    inputs:
      apply:
        description: "Run terraform apply? (false = plan only)"
        required: true
        type: boolean
        default: true
      bootstrap:
        description: "Run Flux CLI bootstrap after apply?"
        required: true
        type: boolean
        default: true

permissions:
  contents: write

concurrency:
  group: create-gke
  cancel-in-progress: true

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_environment_variables: true

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.5"

      - name: Terraform Plan/Apply
        env:
          # GitHub provider needs PAT with scopes: repo + admin:public_key
          GITHUB_TOKEN:        ${{ secrets.GH_TOKEN }}

          # TF variables
          TF_VAR_project:      ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_region:       ${{ secrets.GCP_REGION }}
          TF_VAR_zone:         ${{ secrets.GCP_ZONE }}
          TF_VAR_cluster_name: gke-flux

          # For github provider/module inputs used by your TF
          TF_VAR_github_owner: mexxo-dvp
          TF_VAR_github_repo:  gitops
          TF_VAR_flux_path:    clusters/gke
        run: |
          if [ "${{ inputs.apply }}" = "true" ]; then
            terraform init -input=false
            terraform apply -input=false -auto-approve
          else
            terraform init -backend=false -input=false
            terraform validate
            terraform plan -no-color -input=false
          fi

      - name: Flux bootstrap (CLI)
        if: ${{ inputs.bootstrap == true && inputs.apply == true }}
        env:
          GITHUB_TOKEN:   ${{ secrets.GH_TOKEN }}
          GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
          GOOGLE_REGION:  ${{ secrets.GCP_REGION }}
          CLUSTER_NAME:   gke-flux
        run: |
          # kube-context
          gcloud container clusters get-credentials "$CLUSTER_NAME" --region "$GOOGLE_REGION" --project "$GOOGLE_PROJECT"

          # flux cli
          curl -s https://fluxcd.io/install.sh | sudo bash
          flux check --pre

          # GitOps bootstrap до репо mexxo-dvp/gitops, гілка main, шлях clusters/gke
          flux bootstrap github \
            --owner=mexxo-dvp \
            --repository=gitops \
            --branch=main \
            --path=clusters/gke \
            --personal \
            --token-auth
          flux reconcile source git flux-system -n flux-system
          flux reconcile kustomization flux-system -n flux-system --with-source
