name: Create GKE + Flux

on:
  workflow_dispatch:
    inputs:
      apply:
        description: "Run terraform apply? (false = plan only)"
        required: true
        type: boolean
        default: true

permissions:
  contents: write

concurrency:
  group: create-gke
  cancel-in-progress: true

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_environment_variables: true

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.5"

      - name: Where am I?
        run: |
          pwd; ls -la
          find . -maxdepth 2 -name "*.tf" -print

      - name: Terraform Plan/Apply
        env:
          # базові змінні для створення кластера
          TF_VAR_project_id:         ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_region:             ${{ secrets.GCP_REGION }}
          TF_VAR_zone:               ${{ secrets.GCP_ZONE }}
          TF_VAR_cluster_name:       gke-flux

          # ↓↓↓ важливо: змінні для модуля flux_bootstrap_gke, щоб TF не чекав вводу
          TF_VAR_github_owner:       mexxo-dvp
          TF_VAR_github_repository:  gitops
          TF_VAR_flux_path:          clusters/gke
          TF_VAR_github_token:       ${{ secrets.GH_TOKEN }}

          # для провайдера integrations/github
          GITHUB_TOKEN:              ${{ secrets.GH_TOKEN }}
        run: |
          if [ "${{ inputs.apply }}" = "true" ]; then
            terraform init -input=false
            terraform apply -input=false -auto-approve
          else
            terraform init -backend=false -input=false
            terraform validate
            terraform plan -no-color -input=false
          fi