name: Create GKE + Flux

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_environment_variables: true

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.5"

      - name: Export env to GITHUB_ENV
        run: |
          echo "GOOGLE_PROJECT=${{ secrets.GCP_PROJECT_ID }}" >> "$GITHUB_ENV"
          echo "GOOGLE_REGION=${{ secrets.GCP_REGION }}"       >> "$GITHUB_ENV"
          echo "GOOGLE_ZONE=${{ secrets.GCP_ZONE }}"           >> "$GITHUB_ENV"
          echo "CLUSTER_NAME=gke-flux"                         >> "$GITHUB_ENV"
          echo "GH_TOKEN=${{ secrets.GH_TOKEN }}"              >> "$GITHUB_ENV"

      - name: Terraform Init & Apply
        env:
          TF_VAR_project_id:   ${{ env.GOOGLE_PROJECT }}
          TF_VAR_region:       ${{ env.GOOGLE_REGION }}
          TF_VAR_zone:         ${{ env.GOOGLE_ZONE }}
          TF_VAR_cluster_name: ${{ env.CLUSTER_NAME }}
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Flux bootstrap (GitHub)
        env:
          GITHUB_TOKEN:  ${{ env.GH_TOKEN }}
          GOOGLE_PROJECT: ${{ env.GOOGLE_PROJECT }}
          GOOGLE_REGION:  ${{ env.GOOGLE_REGION }}
          CLUSTER_NAME:   ${{ env.CLUSTER_NAME }}
        run: |
          if [ -z "${GITHUB_TOKEN}" ]; then
            echo "GH_TOKEN is empty — skipping Flux bootstrap"
            exit 0
          fi
          gcloud container clusters get-credentials "${CLUSTER_NAME}" --region "${GOOGLE_REGION}" --project "${GOOGLE_PROJECT}"
          curl -s https://fluxcd.io/install.sh | sudo bash
          flux check --pre
          flux bootstrap github --owner=mexxo-dvp --repository=gitops --branch=main --path=clusters/gke --personal
